//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arachne_Framework.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Arachne_Framework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///                                                                                 .d+                
        ///                                                                                .h+                 
        ///             `                                     -`                          .do`                 
        ///            .sh+.                                  mo                         .ds`                  
        ///              -smh+.                               dd`                       -dy`                   
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AsciiSpiderArt {
            get {
                return ResourceManager.GetString("AsciiSpiderArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                   _..._                                                 
        ///                               .-&apos;_..._&apos;&apos;.                                              
        ///                             .&apos; .&apos;      &apos;.\  .             _..._         __.....__      
        ///                            / .&apos;           .&apos;|           .&apos;     &apos;.   .-&apos;&apos;         &apos;.    
        ///          .-,.--.          . &apos;            &lt;  |          .   .-.   . /     .-&apos;&apos;&quot;&apos;-.  `.  
        ///    __    |  .-. |    __   | |             | |          |  &apos;   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AsciiSpiderArt03 {
            get {
                return ResourceManager.GetString("AsciiSpiderArt03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///░█████╗░██████╗░░█████╗░░█████╗░██╗░░██╗███╗░░██╗███████╗
        ///██╔══██╗██╔══██╗██╔══██╗██╔══██╗██║░░██║████╗░██║██╔════╝
        ///███████║██████╔╝███████║██║░░╚═╝███████║██╔██╗██║█████╗░░
        ///██╔══██║██╔══██╗██╔══██║██║░░██╗██╔══██║██║╚████║██╔══╝░░
        ///██║░░██║██║░░██║██║░░██║╚█████╔╝██║░░██║██║░╚███║███████╗
        ///╚═╝░░╚═╝╚═╝░░╚═╝╚═╝░░╚═╝░╚════╝░╚═╝░░╚═╝╚═╝░░╚══╝╚══════╝.
        /// </summary>
        internal static string AsciiSpiderText {
            get {
                return ResourceManager.GetString("AsciiSpiderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    _____                 _     ____                 _    _                  _ 
        ///  / ____|               | |   |  _ \               | |  | |                | |
        /// | |  __  ___   ___   __| |   | |_) |_   _  ___    | |  | |___  ___ _ __   | |
        /// | | |_ |/ _ \ / _ \ / _` |   |  _ &lt;| | | |/ _ \   | |  | / __|/ _ \ &apos;__|  | |
        /// | |__| | (_) | (_) | (_| |   | |_) | |_| |  __/   | |__| \__ \  __/ |     |_|
        ///  \_____|\___/ \___/ \__,_|   |____/ \__, |\___|    \____/|___/\___|_|     (_)
        ///                                 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AsciiSpiderText_ClosingMenuText {
            get {
                return ResourceManager.GetString("AsciiSpiderText_ClosingMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    ▄████████    ▄████████    ▄████████  ▄████████    ▄█    █▄    ███▄▄▄▄      ▄████████ 
        ///  ███    ███   ███    ███   ███    ███ ███    ███   ███    ███   ███▀▀▀██▄   ███    ███ 
        ///  ███    ███   ███    ███   ███    ███ ███    █▀    ███    ███   ███   ███   ███    █▀  
        ///  ███    ███  ▄███▄▄▄▄██▀   ███    ███ ███         ▄███▄▄▄▄███▄▄ ███   ███  ▄███▄▄▄     
        ///▀███████████ ▀▀███▀▀▀▀▀   ▀███████████ ███        ▀▀███▀▀▀▀███▀  ███   ███ ▀▀███▀▀▀     
        ///  ███    ███ ▀███████████   ███    ███ ███    █▄    ███    ███ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AsciiSpiderText04 {
            get {
                return ResourceManager.GetString("AsciiSpiderText04", resourceCulture);
            }
        }
    }
}
